portainer:
  container_name: portainer
  image: portainer/portainer:1.22.0 # Change this to the latest version if need be
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /opt/portainer:/data portainer/portainer
  ports:
  - "9000:9000"
